.PHONY : all 

c6288_2:
	g++ -O3 -std=c++2a c6288-2.cpp -L. -lcflobdd -o c6288_2

c6288_10:
	g++ -O3 -std=c++2a c6288-10.cpp -L. -lcflobdd -o c6288_10

c6288_9:
	g++ -O3 -std=c++2a c6288-9.cpp -L. -lcflobdd -o c6288_9

c6288_8:
	g++ -O3 -std=c++2a c6288-8.cpp -L. -lcflobdd -o c6288_8

c6288_11:
	g++ -O3 -std=c++2a c6288-11.cpp -L. -lcflobdd -o c6288_11

c6288_12:
	g++ -O3 -std=c++2a c6288-12.cpp -L. -lcflobdd -o c6288_12

c432:
	g++ -O3 -std=c++2a c432.cpp -L. -lcflobdd -o c432

c880:
	g++ -O3 -std=c++2a c880.cpp -L. -lcflobdd -o c880

c17:
	g++ -O3 -std=c++2a c17.cpp -L. -lcflobdd -o c17

dartes:
	g++ -O3 -std=c++2a dartes.cpp -L. -lcflobdd -o dartes

dlx1_c:
	g++ -g -std=c++2a dlx1_c.cpp -L. -lcflobdd -o dlx1_c

parity:
	g++ -O3 -std=c++2a parity.cpp -L. -lcflobdd -o parity

product:
	g++ -O3 -std=c++2a product.cpp -L. -lcflobdd -o product
	
all:  c6288_10 c432 c17 c6288_9 c6288_8 c6288_11 c6288_12 parity product dlx1_c c880 dartes 
clean: 
	rm c6288_10 c432 c17 c6288_9 c6288_8 c6288_11 c6288_12 parity product dlx1_c c880 dartes 
