.PHONY : all 
DIR = /Users/meghana/Desktop/Meghana/Research/CUDD/cudd-3.0.0
REL_DIR = ../../cudd-3.0.0

c6288_10:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c6288_10.o -MD -MP -MF c6288_10.Tpo -c -o c6288_10.o `test -f 'c6288_10.cc' || echo './'`c6288_10.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c6288_10 c6288_10.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

c6288_9:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c6288_9.o -MD -MP -MF c6288_9.Tpo -c -o c6288_9.o `test -f 'c6288_9.cc' || echo './'`c6288_9.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c6288_9 c6288_9.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

c6288_8:
	rm -f c6288_8.o c6288_8 c6288_8.Tpo
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c6288_8.o -MD -MP -MF c6288_8.Tpo -c -o c6288_8.o `test -f 'c6288_8.cc' || echo './'`c6288_8.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c6288_8 c6288_8.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

c6288_11:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c6288_11.o -MD -MP -MF c6288_11.Tpo -c -o c6288_11.o `test -f 'c6288_11.cc' || echo './'`c6288_11.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c6288_11 c6288_11.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

c6288_12:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c6288_12.o -MD -MP -MF c6288_12.Tpo -c -o c6288_12.o `test -f 'c6288_12.cc' || echo './'`c6288_12.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c6288_12 c6288_12.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

c6288_16:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c6288_16.o -MD -MP -MF c6288_16.Tpo -c -o c6288_16.o `test -f 'c6288_16.cc' || echo './'`c6288_16.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c6288_16 c6288_16.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

c6288_2:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c6288_2.o -MD -MP -MF c6288_2.Tpo -c -o c6288_2.o `test -f 'c6288_2.cc' || echo './'`c6288_2.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c6288_2 c6288_2.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

c432:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c432.o -MD -MP -MF c432.Tpo -c -o c432.o `test -f 'c432.cc' || echo './'`c432.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c432 c432.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

c880:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c880.o -MD -MP -MF c880.Tpo -c -o c880.o `test -f 'c880.cc' || echo './'`c880.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c880 c880.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

c17:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT c17.o -MD -MP -MF c17.Tpo -c -o c17.o `test -f 'c17.cc' || echo './'`c17.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o c17 c17.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

dartes:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT dartes.o -MD -MP -MF dartes.Tpo -c -o dartes.o `test -f 'dartes.cc' || echo './'`dartes.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o dartes dartes.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

dlx1_c:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT dartes.o -MD -MP -MF dlx1_c.Tpo -c -o dlx1_c.o `test -f 'dlx1_c.cc' || echo './'`dlx1_c.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o dlx1_c dlx1_c.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

parity:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT parity.o -MD -MP -MF parity.Tpo -c -o parity.o `test -f 'parity.cc' || echo './'`parity.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o parity parity.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

product:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT product.o -MD -MP -MF product.Tpo -c -o product.o `test -f 'product.cc' || echo './'`product.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o product product.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

nqueens:
	g++ -O3 -DHAVE_CONFIG_H -I./$(DIR)  -I./$(DIR)/cudd -I./$(DIR)/mtr -I./$(DIR)/epd -I./$(DIR)/st   -Wall -Wextra  -Wl -std=c++0x -g -O3 -MT nqueens.o -MD -MP -MF nqueens.Tpo -c -o nqueens.o `test -f 'nqueens.cc' || echo './'`nqueens.cc
	/bin/bash ./$(REL_DIR)/libtool  --tag=CXX   --mode=link g++  -Wall -Wextra -std=c++0x -g -O3   -o nqueens nqueens.o $(DIR)/cplusplus/libobj.la $(DIR)/cudd/libcudd.la 

dep:
	cd ../../cudd-3.0.0/ && make all && cd ../examples/Traces
	
all:  c6288_10 c432 c17 c6288_9 c6288_8 c6288_11 c6288_12 parity product dlx1_c c880 dartes 
clean: 
	rm *.o *.Tpo c6288_10 c432 c17 c6288_9 c6288_8 c6288_11 c6288_12 parity product dlx1_c c880 dartes 
